export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';
export const COUNTER_RESET = 'COUNTER_RESET';

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_UNAUTHORIZED = 'AUTH_LOGIN_UNAUTHORIZED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS'

export const NETWORK_FAILURE = 'NETWORK_FAILURE';

export const FETCH_ASYNC_HERODATA = 'FETCH_ASYNC_HERODATA';
export const FETCH_ASYNC_HERODATA_SUCCESS = 'FETCH_ASYNC_HERODATA_SUCCESS';
export const FETCH_ASYNC_HERODATA_FAILURE = 'FETCH_ASYNC_HERODATA_FAILURE';